# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NutHe0s3OsaP_Ejq83Yi5Ekm75FTXpW
"""

pip install requests beautifulsoup4 pandas
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. Define the target URL
url = "http://books.toscrape.com/catalogue/category/books/science_22/index.html"

# 2. Fetch the page
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# 3. Create lists to store our extracted data
titles = []
prices = []
availability = []

# 4. Navigate the hierarchical HTML structure (finding all book containers)
books = soup.find_all("article", class_="product_pod")

for book in books:
    # Extract Title (grabbing the 'title' attribute from the anchor tag)
    title = book.h3.a["title"]
    titles.append(title)

    # Extract Price and clean the text (removing the £ symbol)
    price_text = book.find("p", class_="price_color").text
    cleaned_price = float(price_text.replace("£", ""))
    prices.append(cleaned_price)

    # Extract Stock Status
    stock = book.find("p", class_="instock availability").text.strip()
    availability.append(stock)

# 5. Data Processing: Convert to a structured format using Pandas
df = pd.DataFrame({
    "Book_Title": titles,
    "Price_GBP": prices,
    "Availability": availability
})

# 6. Deliver the high-quality dataset
df.to_csv("science_books_data.csv", index=False)
print("Data successfully scraped and saved to science_books_data.csv!")

import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. Define the target URL
url = "http://books.toscrape.com/catalogue/category/books/science_22/index.html"

# 2. Fetch the page
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# 3. Create lists to store our extracted data
titles = []
prices = []
availability = []

# 4. Navigate the hierarchical HTML structure (finding all book containers)
books = soup.find_all("article", class_="product_pod")

for book in books:
    # Extract Title (grabbing the 'title' attribute from the anchor tag)
    title = book.h3.a["title"]
    titles.append(title)

    # Extract Price and clean the text (removing the £ symbol and the Â character)
    price_text = book.find("p", class_="price_color").text
    cleaned_price = float(price_text.replace("£", "").replace("Â", ""))
    prices.append(cleaned_price)

    # Extract Stock Status
    stock = book.find("p", class_="instock availability").text.strip()
    availability.append(stock)

# 5. Data Processing: Convert to a structured format using Pandas
df = pd.DataFrame({
    "Book_Title": titles,
    "Price_GBP": prices,
    "Availability": availability
})

# 6. Deliver the high-quality dataset
df.to_csv("science_books_data.csv", index=False)
print("Data successfully scraped and saved to science_books_data.csv!")