# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOf-cXMgSSOlmghJ55IjniHVUp3BxVFl
"""

pip install selenium webdriver-manager pandas

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# 1. Set up the Selenium WebDriver (This opens an automated Chrome browser)
print("Starting the browser...")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# 2. Go to the target URL that has infinite scroll
url = "http://quotes.toscrape.com/scroll"
driver.get(url)

# Wait a moment for the initial JavaScript to load the first batch of quotes
time.sleep(2)

# 3. Simulate a human scrolling down to trigger the AJAX/infinite scroll
print("Scrolling down to load more content...")
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

# Wait for the new batch of quotes to load after scrolling
time.sleep(2)

# 4. Extract the data using Selenium's locators
quotes_data = []
authors_data = []

# Find all the containers holding the quotes
quote_elements = driver.find_elements(By.CLASS_NAME, "quote")

for element in quote_elements:
    # Extract the text and the author from inside each container
    quote_text = element.find_element(By.CLASS_NAME, "text").text
    author_name = element.find_element(By.CLASS_NAME, "author").text

    quotes_data.append(quote_text)
    authors_data.append(author_name)

# 5. Close the automated browser
driver.quit()

# 6. Process and save to a structured CSV format using Pandas
df = pd.DataFrame({
    "Quote": quotes_data,
    "Author": authors_data
})

df.to_csv("dynamic_quotes_data.csv", index=False)
print(f"Success! Scraped {len(df)} quotes and saved to dynamic_quotes_data.csv.")

!apt-get update
!apt-get install -y chromium-browser
!apt-get install -y chromium-chromedriver
!pip install selenium

from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

# 1. Set up the headless browser options (Crucial for Google Colab)
options = webdriver.ChromeOptions()
options.add_argument('--headless') # Runs Chrome invisibly
options.add_argument('--no-sandbox') # Bypasses OS security model
options.add_argument('--disable-dev-shm-usage') # Overcomes limited resource problems

print("Starting the headless browser...")
# Initialize the driver with our new options
driver = webdriver.Chrome(options=options)

# 2. Go to the target URL that has infinite scroll
url = "http://quotes.toscrape.com/scroll"
driver.get(url)

# Wait a moment for the initial JavaScript to load
time.sleep(2)

# 3. Simulate a human scrolling down to trigger the AJAX/infinite scroll
print("Scrolling down to load more content...")
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

# Wait for the new batch of quotes to load after scrolling
time.sleep(2)

# 4. Extract the data using Selenium's locators
quotes_data = []
authors_data = []

# Find all the containers holding the quotes
quote_elements = driver.find_elements(By.CLASS_NAME, "quote")

for element in quote_elements:
    # Extract the text and the author from inside each container
    quote_text = element.find_element(By.CLASS_NAME, "text").text
    author_name = element.find_element(By.CLASS_NAME, "author").text

    quotes_data.append(quote_text)
    authors_data.append(author_name)

# 5. Close the automated browser
driver.quit()

# 6. Process and save to a structured CSV format using Pandas
df = pd.DataFrame({
    "Quote": quotes_data,
    "Author": authors_data
})

df.to_csv("dynamic_quotes_data.csv", index=False)
print(f"Success! Scraped {len(df)} quotes and saved to dynamic_quotes_data.csv.")

from selenium import webdriver
from selenium.webdriver.chrome.service import Service # <-- Added this new import
from selenium.webdriver.common.by import By
import pandas as pd
import time

# 1. Set up the headless browser options
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

print("Starting the headless browser...")

# 1.5 Tell Selenium EXACTLY where Colab installed the driver
service = Service('/usr/bin/chromedriver')

# Initialize the driver with BOTH the service path and our options
driver = webdriver.Chrome(service=service, options=options)

# 2. Go to the target URL that has infinite scroll
url = "http://quotes.toscrape.com/scroll"
driver.get(url)

# Wait a moment for the initial JavaScript to load
time.sleep(2)

# 3. Simulate a human scrolling down to trigger the AJAX/infinite scroll
print("Scrolling down to load more content...")
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

# Wait for the new batch of quotes to load after scrolling
time.sleep(2)

# 4. Extract the data using Selenium's locators
quotes_data = []
authors_data = []

# Find all the containers holding the quotes
quote_elements = driver.find_elements(By.CLASS_NAME, "quote")

for element in quote_elements:
    # Extract the text and the author from inside each container
    quote_text = element.find_element(By.CLASS_NAME, "text").text
    author_name = element.find_element(By.CLASS_NAME, "author").text

    quotes_data.append(quote_text)
    authors_data.append(author_name)

# 5. Close the automated browser
driver.quit()

# 6. Process and save to a structured CSV format using Pandas
df = pd.DataFrame({
    "Quote": quotes_data,
    "Author": authors_data
})

df.to_csv("dynamic_quotes_data.csv", index=False)
print(f"Success! Scraped {len(df)} quotes and saved to dynamic_quotes_data.csv.")

!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
!apt-get update
!apt-get install -y google-chrome-stable
!pip install selenium webdriver-manager pandas

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# 1. Set up the headless browser options
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

print("Starting the official headless Chrome...")

# 2. Automatically install the right driver and initialize Selenium
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# 3. Go to the target URL that has infinite scroll
url = "http://quotes.toscrape.com/scroll"
driver.get(url)

# Wait a moment for the initial JavaScript to load
time.sleep(2)

# 4. Simulate a human scrolling down to trigger the AJAX/infinite scroll
print("Scrolling down to load more content...")
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

# Wait for the new batch of quotes to load after scrolling
time.sleep(2)

# 5. Extract the data using Selenium's locators
quotes_data = []
authors_data = []

# Find all the containers holding the quotes
quote_elements = driver.find_elements(By.CLASS_NAME, "quote")

for element in quote_elements:
    # Extract the text and the author from inside each container
    quote_text = element.find_element(By.CLASS_NAME, "text").text
    author_name = element.find_element(By.CLASS_NAME, "author").text

    quotes_data.append(quote_text)
    authors_data.append(author_name)

# 6. Close the automated browser
driver.quit()

# 7. Process and save to a structured CSV format using Pandas
df = pd.DataFrame({
    "Quote": quotes_data,
    "Author": authors_data
})

df.to_csv("dynamic_quotes_data.csv", index=False)
print(f"Success! Scraped {len(df)} quotes and saved to dynamic_quotes_data.csv.")

df.to_csv("dynamic_quotes_data.csv", index=False, encoding="utf-8-sig")